alias list_buckets="python3 $PWD/list_buckets.py"
alias list_objects="python3 $PWD/list_objects.py"
alias download="python3 $PWD/download.py"
alias sync="python3 $PWD/sync.py"
alias upload_file="python3 $PWD/upload_file.py"